/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dict.dao.service.base;

import com.dict.dao.model.DictCollectionAlpacaJS;
import com.dict.dao.service.DictCollectionAlpacaJSLocalService;
import com.dict.dao.service.persistence.DictCollectionAlpacaJSPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dict collection alpaca j s local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dict.dao.service.impl.DictCollectionAlpacaJSLocalServiceImpl}.
 * </p>
 *
 * @author binhth
 * @see com.dict.dao.service.impl.DictCollectionAlpacaJSLocalServiceImpl
 * @see com.dict.dao.service.DictCollectionAlpacaJSLocalServiceUtil
 * @generated
 */
public abstract class DictCollectionAlpacaJSLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements DictCollectionAlpacaJSLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.dict.dao.service.DictCollectionAlpacaJSLocalServiceUtil} to access the dict collection alpaca j s local service.
	 */

	/**
	 * Adds the dict collection alpaca j s to the database. Also notifies the appropriate model listeners.
	 *
	 * @param dictCollectionAlpacaJS the dict collection alpaca j s
	 * @return the dict collection alpaca j s that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DictCollectionAlpacaJS addDictCollectionAlpacaJS(
		DictCollectionAlpacaJS dictCollectionAlpacaJS)
		throws SystemException {
		dictCollectionAlpacaJS.setNew(true);

		return dictCollectionAlpacaJSPersistence.update(dictCollectionAlpacaJS);
	}

	/**
	 * Creates a new dict collection alpaca j s with the primary key. Does not add the dict collection alpaca j s to the database.
	 *
	 * @param dictCollectionId the primary key for the new dict collection alpaca j s
	 * @return the new dict collection alpaca j s
	 */
	@Override
	public DictCollectionAlpacaJS createDictCollectionAlpacaJS(
		long dictCollectionId) {
		return dictCollectionAlpacaJSPersistence.create(dictCollectionId);
	}

	/**
	 * Deletes the dict collection alpaca j s with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dictCollectionId the primary key of the dict collection alpaca j s
	 * @return the dict collection alpaca j s that was removed
	 * @throws PortalException if a dict collection alpaca j s with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DictCollectionAlpacaJS deleteDictCollectionAlpacaJS(
		long dictCollectionId) throws PortalException, SystemException {
		return dictCollectionAlpacaJSPersistence.remove(dictCollectionId);
	}

	/**
	 * Deletes the dict collection alpaca j s from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dictCollectionAlpacaJS the dict collection alpaca j s
	 * @return the dict collection alpaca j s that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DictCollectionAlpacaJS deleteDictCollectionAlpacaJS(
		DictCollectionAlpacaJS dictCollectionAlpacaJS)
		throws SystemException {
		return dictCollectionAlpacaJSPersistence.remove(dictCollectionAlpacaJS);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(DictCollectionAlpacaJS.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return dictCollectionAlpacaJSPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.dict.dao.model.impl.DictCollectionAlpacaJSModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return dictCollectionAlpacaJSPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.dict.dao.model.impl.DictCollectionAlpacaJSModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return dictCollectionAlpacaJSPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return dictCollectionAlpacaJSPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return dictCollectionAlpacaJSPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public DictCollectionAlpacaJS fetchDictCollectionAlpacaJS(
		long dictCollectionId) throws SystemException {
		return dictCollectionAlpacaJSPersistence.fetchByPrimaryKey(dictCollectionId);
	}

	/**
	 * Returns the dict collection alpaca j s with the primary key.
	 *
	 * @param dictCollectionId the primary key of the dict collection alpaca j s
	 * @return the dict collection alpaca j s
	 * @throws PortalException if a dict collection alpaca j s with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public DictCollectionAlpacaJS getDictCollectionAlpacaJS(
		long dictCollectionId) throws PortalException, SystemException {
		return dictCollectionAlpacaJSPersistence.findByPrimaryKey(dictCollectionId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return dictCollectionAlpacaJSPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dict collection alpaca j ses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.dict.dao.model.impl.DictCollectionAlpacaJSModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of dict collection alpaca j ses
	 * @param end the upper bound of the range of dict collection alpaca j ses (not inclusive)
	 * @return the range of dict collection alpaca j ses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<DictCollectionAlpacaJS> getDictCollectionAlpacaJSs(int start,
		int end) throws SystemException {
		return dictCollectionAlpacaJSPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dict collection alpaca j ses.
	 *
	 * @return the number of dict collection alpaca j ses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getDictCollectionAlpacaJSsCount() throws SystemException {
		return dictCollectionAlpacaJSPersistence.countAll();
	}

	/**
	 * Updates the dict collection alpaca j s in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param dictCollectionAlpacaJS the dict collection alpaca j s
	 * @return the dict collection alpaca j s that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DictCollectionAlpacaJS updateDictCollectionAlpacaJS(
		DictCollectionAlpacaJS dictCollectionAlpacaJS)
		throws SystemException {
		return dictCollectionAlpacaJSPersistence.update(dictCollectionAlpacaJS);
	}

	/**
	 * Returns the dict collection alpaca j s local service.
	 *
	 * @return the dict collection alpaca j s local service
	 */
	public com.dict.dao.service.DictCollectionAlpacaJSLocalService getDictCollectionAlpacaJSLocalService() {
		return dictCollectionAlpacaJSLocalService;
	}

	/**
	 * Sets the dict collection alpaca j s local service.
	 *
	 * @param dictCollectionAlpacaJSLocalService the dict collection alpaca j s local service
	 */
	public void setDictCollectionAlpacaJSLocalService(
		com.dict.dao.service.DictCollectionAlpacaJSLocalService dictCollectionAlpacaJSLocalService) {
		this.dictCollectionAlpacaJSLocalService = dictCollectionAlpacaJSLocalService;
	}

	/**
	 * Returns the dict collection alpaca j s remote service.
	 *
	 * @return the dict collection alpaca j s remote service
	 */
	public com.dict.dao.service.DictCollectionAlpacaJSService getDictCollectionAlpacaJSService() {
		return dictCollectionAlpacaJSService;
	}

	/**
	 * Sets the dict collection alpaca j s remote service.
	 *
	 * @param dictCollectionAlpacaJSService the dict collection alpaca j s remote service
	 */
	public void setDictCollectionAlpacaJSService(
		com.dict.dao.service.DictCollectionAlpacaJSService dictCollectionAlpacaJSService) {
		this.dictCollectionAlpacaJSService = dictCollectionAlpacaJSService;
	}

	/**
	 * Returns the dict collection alpaca j s persistence.
	 *
	 * @return the dict collection alpaca j s persistence
	 */
	public DictCollectionAlpacaJSPersistence getDictCollectionAlpacaJSPersistence() {
		return dictCollectionAlpacaJSPersistence;
	}

	/**
	 * Sets the dict collection alpaca j s persistence.
	 *
	 * @param dictCollectionAlpacaJSPersistence the dict collection alpaca j s persistence
	 */
	public void setDictCollectionAlpacaJSPersistence(
		DictCollectionAlpacaJSPersistence dictCollectionAlpacaJSPersistence) {
		this.dictCollectionAlpacaJSPersistence = dictCollectionAlpacaJSPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.dict.dao.model.DictCollectionAlpacaJS",
			dictCollectionAlpacaJSLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.dict.dao.model.DictCollectionAlpacaJS");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return DictCollectionAlpacaJS.class;
	}

	protected String getModelClassName() {
		return DictCollectionAlpacaJS.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = dictCollectionAlpacaJSPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.dict.dao.service.DictCollectionAlpacaJSLocalService.class)
	protected com.dict.dao.service.DictCollectionAlpacaJSLocalService dictCollectionAlpacaJSLocalService;
	@BeanReference(type = com.dict.dao.service.DictCollectionAlpacaJSService.class)
	protected com.dict.dao.service.DictCollectionAlpacaJSService dictCollectionAlpacaJSService;
	@BeanReference(type = DictCollectionAlpacaJSPersistence.class)
	protected DictCollectionAlpacaJSPersistence dictCollectionAlpacaJSPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private DictCollectionAlpacaJSLocalServiceClpInvoker _clpInvoker = new DictCollectionAlpacaJSLocalServiceClpInvoker();
}